// Auto-generated by scripts/scrape-calendar.js — do not edit by hand.
// Source: nautiljon.com (FR release dates)
// Generated: 2026-05-26T18:07:04.498Z
const calendar2026 = [
  { mangaId: 6, num: 37, date: "2026-02-25", title: "Black Clover" },
  { mangaId: 14, num: 22, date: "2026-04-08", title: "Dandadan" },
  { mangaId: 31, num: 77, date: "2026-04-17", title: "Kingdom" },
  { mangaId: 8, num: 32, date: "2026-05-13", title: "Blue Lock" },
  { mangaId: 5, num: 5, date: "2026-05-20", title: "Berserk" },
  { mangaId: 8, num: 33, date: "2026-06-10", title: "Blue Lock" },
  { mangaId: 5, num: 43, date: "2026-07-01", title: "Berserk" },
  { mangaId: 14, num: 23, date: "2026-07-01", title: "Dandadan" },
  { mangaId: 34, num: 14, date: "2026-07-10", title: "Made in Abyss" },
  { mangaId: 31, num: 9, date: "2026-07-17", title: "Kingdom" }
];
